title: Emacs
url: http://inclusa.github.io # site url
baseurl: "/emacs" # apply repo name if use it under gh-pages branch

date_format: "%Y-%m-%d"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics:
disqus_shortname:
